 ar rcs ./redis/src/libredis.a ./redis/src/lzf_d.o\
 ./redis/src/release.o\
 ./redis/src/t_zset.o\
 ./redis/src/sds.o\
 ./redis/src/bitops.o\
 ./redis/src/zipmap.o\
 ./redis/src/networking.o\
 ./redis/src/lzf_c.o\
 ./redis/src/bio.o\
 ./redis/src/endianconv.o\
 ./redis/src/zmalloc.o\
 ./redis/src/anet.o\
 ./redis/src/slowlog.o\
 ./redis/src/util.o\
 ./redis/src/debug.o\
 ./redis/src/redis.o\
 ./redis/src/aof.o\
 ./redis/src/object.o\
 ./redis/src/memtest.o\
 ./redis/src/redis-check-aof.o\
 ./redis/src/t_list.o\
 ./redis/src/rdb.o\
 ./redis/src/pubsub.o\
 ./redis/src/sha1.o\
 ./redis/src/syncio.o\
 ./redis/src/db.o\
 ./redis/src/t_set.o\
 ./redis/src/sort.o\
 ./redis/src/pqsort.o\
 ./redis/src/t_hash.o\
 ./redis/src/replication.o\
 ./redis/src/crc64.o\
 ./redis/src/intset.o\
 ./redis/src/rand.o\
 ./redis/src/multi.o\
 ./redis/src/redis-check-dump.o\
 ./redis/src/migrate.o\
 ./redis/src/redis-cli.o\
 ./redis/src/config.o\
 ./redis/src/scripting.o\
 ./redis/src/ae.o\
 ./redis/src/dict.o\
 ./redis/src/t_string.o\
 ./redis/src/redis-benchmark.o\
 ./redis/src/ziplist.o\
 ./redis/src/adlist.o\
 ./redis/src/rio.o\
 ./redis/deps/lua/src/ltm.o\
 ./redis/deps/lua/src/lua_struct.o\
 ./redis/deps/lua/src/ldo.o\
 ./redis/deps/lua/src/lgc.o\
 ./redis/deps/lua/src/luac.o\
 ./redis/deps/lua/src/lmem.o\
 ./redis/deps/lua/src/ldump.o\
 ./redis/deps/lua/src/lcode.o\
 ./redis/deps/lua/src/print.o\
 ./redis/deps/lua/src/liolib.o\
 ./redis/deps/lua/src/lobject.o\
 ./redis/deps/lua/src/strbuf.o\
 ./redis/deps/lua/src/linit.o\
 ./redis/deps/lua/src/lfunc.o\
 ./redis/deps/lua/src/lbaselib.o\
 ./redis/deps/lua/src/lmathlib.o\
 ./redis/deps/lua/src/lparser.o\
 ./redis/deps/lua/src/ldblib.o\
 ./redis/deps/lua/src/ldebug.o\
 ./redis/deps/lua/src/lopcodes.o\
 ./redis/deps/lua/src/loslib.o\
 ./redis/deps/lua/src/lstrlib.o\
 ./redis/deps/lua/src/lvm.o\
 ./redis/deps/lua/src/lundump.o\
 ./redis/deps/lua/src/lstate.o\
 ./redis/deps/lua/src/lzio.o\
 ./redis/deps/lua/src/lua_cmsgpack.o\
 ./redis/deps/lua/src/lua.o\
 ./redis/deps/lua/src/lstring.o\
 ./redis/deps/lua/src/lauxlib.o\
 ./redis/deps/lua/src/ltablib.o\
 ./redis/deps/lua/src/lapi.o\
 ./redis/deps/lua/src/ltable.o\
 ./redis/deps/lua/src/llex.o\
 ./redis/deps/lua/src/loadlib.o\
 ./redis/deps/lua/src/lua_cjson.o\
 ./redis/deps/linenoise/linenoise.o\
